id: I750436E5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T05:52:50+00:00'
last_modified: '2022-06-08T13:01:43.570443+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN6934
  title: བོད་ཀྱི་ཡུལ་སྲོལ་རྣམ་ཤད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    588D:
      image_group_id: I3CN6936
      title: Volume 1 of bod kyi yul srol rnam shad/
      total_pages: 438
      order: 1
      base_file: 588D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
