id: P006963
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W3CN6934
  title: བོད་ཀྱི་ཡུལ་སྲོལ་རྣམ་ཤད།
  author: ''
  volumes:
    4605c771bd764ff7bd1b9448918dedaa:
      image_group_id: I3CN6936
      title: Volume 1 of bod kyi yul srol rnam shad/
      volume_number: 1
      total_pages: 438
      base_file: v001.txt
