id: P006963
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN6934
  title: བོད་ཀྱི་ཡུལ་སྲོལ་རྣམ་ཤད།
  author: ''
  volumes:
    96d6a4020d824cbdaf17fa77976c065c:
      image_group_id: I3CN6936
      title: ''
      volume_number: 1
      total_pages: 438
ebook_metadata:
  title: བོད་ཀྱི་ཡུལ་སྲོལ་རྣམ་ཤད།
  author: ''
  sku: P006963
  cover: cover.jpg
  layers:
  - pagination
